spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
    # Example for a specific circuit breaker instance named 'myServiceCircuitBreaker'
    instances:
      myServiceCircuitBreaker:
        slidingWindowSize: 50
        failureRateThreshold: 40
  # HEATH CHECK-UP
  management:
    endpoints:
      web:
        exposure:
          include: health,circuitbreakers
    endpoint:
      health:
        show-details: always